services:
  postgres:
    image: postgres:16-alpine
    container_name: insurhi-cms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: insurhi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - insurhi_cms_pgdata:/var/lib/postgresql/data

volumes:
  insurhi_cms_pgdata:
